# Generated by Django 6.0.2 on 2026-03-03 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorité')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Date limite')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='PrimeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('T1', 'Trimestre 1 (Jan-Mar)'), ('T2', 'Trimestre 2 (Avr-Jun)'), ('T3', 'Trimestre 3 (Jul-Sep)'), ('T4', 'Trimestre 4 (Oct-Déc)'), ('annuel', 'Annuel')], max_length=10)),
                ('year', models.IntegerField(verbose_name='Année')),
                ('total_tasks', models.IntegerField(default=0)),
                ('tasks_on_time', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('prime_amount', models.IntegerField(choices=[(0, 'Pas de prime'), (30000, 'Prime 30 000 FCFA (90%+)'), (100000, 'Prime 100 000 FCFA (100%)')], default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('professeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Évaluation Prime',
                'unique_together': {('professeur', 'period', 'year')},
            },
        ),
    ]
